import { headers } from "next/headers";
import {
  DIGIFREUND_CANONICAL,
  DIGIFREUND_FAQS,
  DIGIFREUND_MORE_CANONICAL,
  DIGIPRIATEL_FAQS,
  DIGIPRITEL_FAQS,
  DIGIPRITEL_ORIGIN,
  ELDER_COMPANION_CANONICALS,
  ELDER_COMPANION_MORE_CANONICALS,
  GROWBYTE_ORIGIN,
  MYFRIEND_JA_FAQS,
  MYFRIEND_FAQS,
  MYFRIEND_JP_ORIGIN,
  isDigipritelHost,
  isMyFriendJpHost,
  isTryMyFriendHost,
  requestHostFromHeaders,
} from "@/lib/elder-companion-seo";

export const dynamic = "force-dynamic";

function faqLines(faqs: typeof DIGIPRITEL_FAQS) {
  return faqs.flatMap((item) => [
    `- ${item.question}`,
    `  ${item.answer}`,
  ]);
}

export async function GET() {
  const headerList = await headers();
  const host = requestHostFromHeaders(headerList);
  const isDigiPritel = isDigipritelHost(host);
  const isTryMyFriend = isTryMyFriendHost(host);
  const isMyFriendJp = isMyFriendJpHost(host);

  const body = isDigiPritel
    ? [
        "# DigiPřítel",
        "",
        "DigiPřítel je AI společník pro seniory dostupný přes běžný telefonní hovor.",
        "Pomáhá seniorům, kteří tráví hodně času o samotě, nabízí přátelskou konverzaci, připomenutí a praktickou podporu v každodenních situacích.",
        "Není potřeba chytrý telefon, aplikace ani internetové připojení.",
        "",
        "## Kanonické stránky",
        `- Přehled projektu: ${ELDER_COMPANION_CANONICALS.cs}`,
        `- Více o projektu: ${ELDER_COMPANION_MORE_CANONICALS.cs}`,
        "",
        "## Jazykové verze",
        `- Čeština: ${ELDER_COMPANION_CANONICALS.cs}`,
        `- English: ${ELDER_COMPANION_CANONICALS.en}`,
        `- Slovenština: ${ELDER_COMPANION_CANONICALS.sk}`,
        `- 日本語: ${ELDER_COMPANION_CANONICALS.ja}`,
        `- Deutsch: ${DIGIFREUND_CANONICAL}`,
        "",
        "## Časté otázky",
        ...faqLines(DIGIPRITEL_FAQS),
        "",
        "## Kontakt",
        "Projekt vyvíjí GrowByte. Kontakt: oliver.cingl@gmail.com",
      ].join("\n")
    : isTryMyFriend
      ? [
          "# MyFriend",
          "",
          "MyFriend is an AI phone companion for seniors available through a regular phone call.",
          "It helps reduce loneliness, offers friendly conversation, reminders, and practical support in everyday situations.",
          "No smartphone, app, or internet connection is required.",
          "",
          "## Canonical pages",
          `- Project overview: ${ELDER_COMPANION_CANONICALS.en}`,
          `- More about the project: ${ELDER_COMPANION_MORE_CANONICALS.en}`,
          "",
          "## Language versions",
          `- English: ${ELDER_COMPANION_CANONICALS.en}`,
          `- Czech: ${ELDER_COMPANION_CANONICALS.cs}`,
          `- Slovak: ${ELDER_COMPANION_CANONICALS.sk}`,
          `- Japanese: ${ELDER_COMPANION_CANONICALS.ja}`,
          `- German: ${DIGIFREUND_CANONICAL}`,
          "",
          "## Frequently asked questions",
          ...faqLines(MYFRIEND_FAQS),
          "",
          "## Contact",
          "Project by GrowByte. Contact: oliver.cingl@gmail.com",
        ].join("\n")
      : isMyFriendJp
        ? [
            "# MyFriend",
            "",
            "MyFriendは、通常の電話で使えるシニア向けAIコンパニオンです。",
            "孤独感の軽減、フレンドリーな会話、リマインダー、日常のサポートを提供します。",
            "スマホ・アプリ・インターネットは不要です。",
            "",
            "## 正規ページ",
            `- プロジェクト概要: ${ELDER_COMPANION_CANONICALS.ja}`,
            `- プロジェクト詳細: ${ELDER_COMPANION_MORE_CANONICALS.ja}`,
            "",
            "## 言語バージョン",
            `- 日本語: ${ELDER_COMPANION_CANONICALS.ja}`,
            `- English: ${ELDER_COMPANION_CANONICALS.en}`,
            `- Čeština: ${ELDER_COMPANION_CANONICALS.cs}`,
            `- Slovenčina: ${ELDER_COMPANION_CANONICALS.sk}`,
            `- Deutsch: ${DIGIFREUND_CANONICAL}`,
            "",
            "## よくある質問",
            ...faqLines(MYFRIEND_JA_FAQS),
            "",
            "## お問い合わせ",
            "GrowByteによるプロジェクト。連絡先: oliver.cingl@gmail.com",
          ].join("\n")
        : [
            "# GrowByte",
            "",
            "GrowByte builds AI products, automation systems, websites, and applied AI tools.",
            "The company works on custom business automation, web applications, and public AI products such as MyFriend / DigiPřítel.",
            "",
            "## Main pages",
            `- Homepage: ${GROWBYTE_ORIGIN}`,
            `- English homepage: ${GROWBYTE_ORIGIN}/en`,
            `- Czech homepage: ${GROWBYTE_ORIGIN}/cs`,
            `- Slovak homepage: ${GROWBYTE_ORIGIN}/sk`,
            `- Japanese homepage: ${GROWBYTE_ORIGIN}/ja`,
            `- Solutions: ${GROWBYTE_ORIGIN}/solutions/en`,
            `- Case studies: ${GROWBYTE_ORIGIN}/case-studies/en`,
            `- Contact: ${GROWBYTE_ORIGIN}/lets-talk`,
            "",
            "## MyFriend / DigiPřítel project",
            "MyFriend is an AI phone companion for seniors. It is designed to reduce loneliness, offer friendly conversation, provide reminders, and help with everyday questions through a normal phone call.",
            "The project does not require a smartphone, app, or internet connection.",
            "",
            "### Canonical localized pages",
            `- Czech canonical: ${DIGIPRITEL_ORIGIN}`,
            `- Czech detail page: ${ELDER_COMPANION_MORE_CANONICALS.cs}`,
            `- English overview: ${ELDER_COMPANION_CANONICALS.en}`,
            `- English detail page: ${ELDER_COMPANION_MORE_CANONICALS.en}`,
            `- Japanese overview: ${MYFRIEND_JP_ORIGIN}`,
            `- Japanese detail page: ${ELDER_COMPANION_MORE_CANONICALS.ja}`,
            `- Slovak overview: ${ELDER_COMPANION_CANONICALS.sk}`,
            `- Slovak detail page: ${ELDER_COMPANION_MORE_CANONICALS.sk}`,
            `- German DigiFreund overview: ${DIGIFREUND_CANONICAL}`,
            `- German DigiFreund detail page: ${DIGIFREUND_MORE_CANONICAL}`,
            "",
            "### English MyFriend FAQ",
            ...faqLines(MYFRIEND_FAQS),
            "",
            "### Japanese MyFriend FAQ",
            ...faqLines(MYFRIEND_JA_FAQS),
            "",
            "### Czech DigiPřítel FAQ",
            ...faqLines(DIGIPRITEL_FAQS),
            "",
            "### Slovak DigiPriateľ FAQ",
            ...faqLines(DIGIPRIATEL_FAQS),
            "",
            "### German DigiFreund FAQ",
            ...faqLines(DIGIFREUND_FAQS),
            "",
            "## Contact",
            "Email: oliver.cingl@gmail.com",
            "Founder / author: Oliver Cingl",
            "",
            "## Crawling notes",
            "Use canonical URLs and hreflang alternates from page metadata and sitemaps.",
            "For Czech search intent, cite the canonical DigiPřítel domain at https://digipritel.cz.",
            "For English MyFriend search intent, cite https://trymyfriend.com.",
            "For Japanese MyFriend search intent, cite https://myfriend.jp.",
          ].join("\n");

  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
